export enum ActionTypes {
  SEND_MESSAGE = 'SEND_MESSAGE',
  START_SEND_MESSAGE = 'START_SEND_MESSAGE',
  SUCCESS_SEND_MESSAGE = 'SUCCESS_SEND_MESSAGE',
  FAILED_SEND_MESSAGE = 'FAILED_SEND_MESSAGE',

  CREATE_USER = 'CREATE_USER',
  START_CREATE_USER = 'START_CREATE_USER',
  SUCCESS_CREATE_USER = 'SUCCESS_CREATE_USER',
  FAILED_CREATE_USER = 'FAILED_CREATE_USER',

  GET_USER = 'GET_USER',
  START_GET_USER = 'START_GET_USER',
  SUCCESS_GET_USER = 'SUCCESS_GET_USER',
  FAILED_GET_USER = 'FAILED_GET_USER'
}
